name: "tests"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Unit tests
      env:
        GOPATH: /home/runner/go
      run: |
        make test
        make vet
    - uses: engineerd/setup-kind@v0.5.0
    - name: Acceptance Tests
      run: |
        make testacc KUBE_CONFIG_PATH="${HOME}/.kube/config"
